### ISSUE TITLE
Playback cursor significantly of sync with audio

### ISSUE THREAD

**Issue by tg73** [sonic-visualiser/sonic-visualiser#13] opened 2021-01-15 17:15 UTC
When playing back audio, the cursor is way out of sync with what you hear. It is very obvious with an audible time instants track, for example.

This happens with SV versions 4.1 and 4.2, but 4.0.1 works correctly. For me, the problem is so severe that 4.1 and 4.2 are unusable, and I have reverted to 4.0.1. I can attempt to provide screen recordings showing the problem if this is useful. I have C++ development experience (but not for several years) so I might be able to do some debugging in Visual Studio if I have access to symbols and source (ie, *not* building from scratch) if an experienced developer on this project has a specific debug scenario in mind.

I'm using Win x64, Windows 10 build 1909

**Comment by cannam** [comment] 2021-01-20 13:09
Hi there - I was about to make the 4.3 release when you reported this - can you first check that, and see whether it behaves any differently? (https://www.sonicvisualiser.org/download.html) Thanks!

**Comment by tg73** [comment] 2021-01-22 13:38
Hi Chris - sorry for the delay. 4.3 behaves the same. Attached is a video captured using OBS. Playback in SV is set to about 25%. You can hear the click from the orange time instants, but it is not in sync with the playback cursor. And the sync seems to vary if you watch the whole clip. Let me know if there's anything else I can do to assist.

[2021-01-22 13-33-30.zip](https://github.com/sonic-visualiser/sonic-visualiser/files/5856140/2021-01-22.13-33-30.zip)

**Comment by tg73** [comment] 2021-02-24 09:54
Any news on this? I'm happy to help if I can.

**Comment by cannam** [comment] 2021-02-25 11:12
I agree, this is a significant issue, I think caused while fixing the failure to apply auditioning effects plugins correctly (which was one of the changes for 4.1). The playback pointer latency now seems to be entirely at the mercy of the audio playback device buffer size, which is not how it should be. I think I hadn't quite twigged because I had been mostly using devices with smaller buffers.

I'll have a look, but it may be a fiddly one.

**Comment by cannam** [comment] 2021-02-25 14:12
Can you test this build and let me know whether it works any better?
https://all-day-breakfast.com/m/sonic-visualiser-4.4-pre1-win64.msi

**Comment by tg73** [comment] 2021-02-25 15:20
From a quick test, that looks much better, but not yet spot on. The cursor is consistently about 0.075 sec of timeline time behind the audio when playing at ~42% speed (this is just an example). So, to be super clear: I hear the sound before the playback cursor reaches it. When I stop playback and measure out my memory of the the visual discrepancy, it corresponds to 0.075 sec of timeline time. The discrepancy does not appear to be affected by playback speed, but of course it's harder to see it at higher playback speeds. Unlike 4.3 et al, the discrepancy appears to be constant, and is much smaller.

Attached is an example playing back at 25% speed.

[2021-02-25 15-17-41.zip](https://github.com/sonic-visualiser/sonic-visualiser/files/6043917/2021-02-25.15-17-41.zip)

**Comment by cannam** [comment] 2021-02-25 16:05
Hm, that's a pity, because in my tests the cursor is now marginally *ahead* of playback when slowed right down - so it's clearly system dependent in some way still.

Can you confirm whether the behaviour in this build is significantly different from 4.0.1? Was 4.0.1 actually spot on, or was it just a lot better than 4.1-4.3?

(As I see it here, 4.0.1 was also slightly ahead of playback just as 4.4-pre1 is for me - in fact I don't think I can tell the two apart here)

**Comment by tg73** [comment] 2021-02-25 18:00
Rather than rely on time instant noises, I've generated a test audio file comprising a repeating sequence of 240 samples of 24khz "square" wave followed by 11760 samples of silence. To me, it looks pretty much bang on in 4.0.1. If the cursor movement was smoother, it might show up a tiny error, but as it stands, it's certainly fit for purpose. Test audio file attached too. And a the same click test with your 4.4-pre1 - and I now agree with you, the cursor is now marginally _ahead_ of playback.

OBS grabs, playing at 25% speed.

[click-test-4.4-pre1.mkv.zip](https://github.com/sonic-visualiser/sonic-visualiser/files/6044917/click-test-4.4-pre1.mkv.zip)

[click240_slience11760_48khz.zip](https://github.com/sonic-visualiser/sonic-visualiser/files/6044900/click240_slience11760_48khz.zip)

[click-test-4.0.1.mkv.zip](https://github.com/sonic-visualiser/sonic-visualiser/files/6044892/click-test-4.0.1.mkv.zip)

**Comment by DiceK-S** [comment] 2021-06-23 04:33
Has this issue been resolved?
I am suffering from the same phenomenon.

In my case, when I load a 4kHz wav file, the graph does not match the audio.
However, if I load a 44.1 kHz wav file and then load a 4 kHz wav file, the problem is temporarily solved.
When I save the file and open it again, though, they do not match again.
I'm a newbie, so I can't help you technically, but I can test it.
I hope my case gives you an idea.

I'll try 4.4-pre1 and 4.0.1 already mentioned.

Im using Win x64, Windows 10 build 19041 and Mac, MacOS 11.4 MBP 13-inch, Early 2015

**Comment by DiceK-S** [comment] 2021-06-23 05:16
I immediately tried 4.4-pre1 and 4.0.1 on Windows only.
The results showed that the same phenomenon occurred with 4.4-pre1, and it worked fine with 4.0.1.

The test method is just to load a 4kHz wav file and actually play it.
In 4.4-pre1, as in 4.3, the synchronization between the graph and the audio is delayed by about 1 second in the audio.

**Comment by cannam** [comment] 2021-07-08 15:09
I see, sounds like the effect is inversely proportional to sampling rate - which gives me something else to go on.

In your case if you loaded something at 44.1 and then something else at 4kHz, it's possible the audio device remained open at 44.1 and the latter file was resampled at playback, hence the delay being 1/10 of what it was if playing something at 4kHz from the start.

**Comment by DiceK-S** [comment] 2021-07-09 00:24
You are right. The delay during playback is so small that you can't feel it, but it is there during slow playback.
It's not a problem for my use, but it's not practical to have a workflow that loads 44.1 files frequently, so I'm currently using version 4.0.1.

**Comment by cannam** [comment] 2021-08-13 16:07
This is addressed in the repo now, and can be tested in the v4.4-pre2 test build available for download currently from https://sonicvisualiser.org/pre/ (a temporary location - I am about to revisit the question of which files get hosted where, as the SoundSoftware code site is still having cert issues and Bintray has ceased operating).

Please give it a try, and add any comments on this issue here. (If you find other problems with this pre-release, please open another issue or drop me a line by email.)

**Comment by DiceK-S** [comment] 2021-08-13 16:19
Thank you very much, cannam. I'll try it out and report back.

**Comment by DiceK-S** [comment] 2021-08-24 07:37
Hi cannam.

I tried v4.4-pre2 on win10 64bit (build 19041).
I was able to use the same 4K sampling rate file as before, with no problem synchronizing the audio and graphs.
I also used a few other functions (data export, etc.) without any problems.

This will no longer be a problem for my use and will be a great solution.
If there is anything else I can do to help, please let me know.
I am looking forward to the release of v4.4.

**Comment by cannam** [comment] 2021-09-30 13:55
Fix is in 4.4, hopefully still working!

**Closed as completed by cannam** 2021-09-30 13:55 UTC
