### ISSUE TITLE
Uses only 1 CPU on M1 Mac

### ISSUE THREAD

**Issue by PyThrrrone** [sonic-visualiser/sonic-visualiser#56] opened 2022-08-06 16:58 UTC
Great Software, but performance is poor.

**Comment by cannam** [comment] 2022-08-08 08:24
Yes - I agree with the comment, though I think the cause is a little different. It's not that it only uses a single core.

SV is indeed a bit sluggish on the ARM Mac - perceptually slower than on other platforms I think, which is ironic considering how fast the computer can be.

At the same time, SV has always been quite pervasively multi-threaded (and indeed multi-process in some cases) and it will happily use any number of cores simultaneously to run analysis plugins while taking others for file decoding, another for audio playback etc. It can easily have dozens of active threads spread across many CPU cores.

However, there is still a single primary GUI thread in which a significant amount of work happens and in particular - and I believe this is the real problem when using the ARM Mac - it makes no use at all of the GPU. All rendering is done on the CPU. It totally lacks the typical pipeline architecture in which the results of analysis work arrive and are assembled for rendering without affecting the GPU-driven update frequency. This hurts badly on the Mac where the integrated GPU is quite fast and the shared memory architecture is clearly intended for a very different rendering style.

I would never write it this way now, and I don't think many developers would. But at the time SV was first written (2006) this was a good decision. Requiring game-like levels of GPU+driver support would have made it far harder to run reliably and debug and support across the main target platforms. It might have worked out ok even then on the Mac, but for Linux (not only a primary target but the one actually used to develop SV) and Windows (always by far the most popular platform among SV users) it would have been prohibitive in terms of support labour.

So this is the problem. But this situation is very unlikely to change meaningfully in SV unless a really substantial amount of funding arrives to change it - it's simply too big an architectural difference. Therefore I'm afraid this report really has to count as an observation rather than an actionable bug report, and I am going to close it, with my apologies.

**Closed as completed by cannam** 2022-08-08 08:24 UTC

**Comment by PyThrrrone** [comment] 2022-08-08 16:16
Thank you, Chris. That makes sense. I just compared SV with sox creating a spectrogram. Sox seams to be even slower and uses only 1 core as well.
I just thought you just have  to switch on a certain compiler parameter.
Anyway, SV gives me spectrograms almost as precise as a piano roll.
Thank you all!
